version: '3.2'

services:
  mysql:
    image: 'mysql:5.7.21'
    container_name: 'mysql_container'
    ports:
      - '33006:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=demo
